<?php

/**
 * API schema for research project
 * API schema for research project
 * PHP version 8.2
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class GeneralController extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation authorizePost
     *
     * Get authorization JWT token.
     *
     *
     * @return Http response
     */
    public function authorizePost()
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing authorizePost as a post method ?');
    }
    /**
     * Operation helloGet
     *
     * Returns \"Hello World!\" phrase.
     *
     *
     * @return Http response
     */
    public function helloGet()
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing helloGet as a get method ?');
    }
}
