<?php

/**
 * API schema for research project
 * API schema for research project
 * PHP version 8.2
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Request;
use Tymon\JWTAuth\Facades\JWTAuth;

class GeneralController extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation authorizePost
     *
     * Get authorization JWT token.
     *
     *
     * @return Http response
     */
    public function authorizePost()
    {
        $authData = json_decode(Request::getContent());
        if ($authData === null) {
            return response(status: 401);
        }

        $username = $authData->username ?? "";
        $password = $authData->passphrase ?? "";

        $userController = new UserController();
        $userController->authenticate($username, $password);

        if ($user = Auth::user()) {
            $token = JWTAuth::fromUser($user);
            return response($token, 200);
        } else {
            return response(status: 401);
        }
    }

    /**
     * Operation helloGet
     *
     * Returns \"Hello World!\" phrase.
     *
     *
     * @return Http response
     */
    public function helloGet()
    {
        return response("Hello World!", 200);
    }
}
